[package]
name = "upl"
version = "0.0.0"
authors = ["7ap"]
edition = "2021"
description = "The intuitive command-line file uploader."
license = "MIT"
repository = "https://github.com/7ap/upl"


[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
reqwest = { version = "0.11.12", features = ["blocking", "multipart"] }
